#!/bin/bash

FIRSTGPIO=
for i in /sys/class/gpio/gpiochip*
do
    [ -d $i ] || continue
    [ -f $i/label ] || continue
    [ -f $i/base ] || continue
    [ `cat $i/label` = 1e780000.gpio ] && FIRSTGPIO=`cat $i/base`
done

if [ -z $FIRSTGPIO ]
then
    echo "GPIO subsystem not initialized: no suitable /sys/class/gpio/gpiochip* entry" 1>&2
    exit 240
fi

# Note: this is GPIO set for REIMU, MUS-A has some GPIOs absent,
# and corresponding LEDs and buttons are served through TinySPI.

case `cat /sys/devices/soc0/family` in
    AST2400)
        . /etc/gpiotab.2400
    ;;
    AST2500)
        . /etc/gpiotab.2500
    ;;
    AST2600)
        . /etc/gpiotab.2600
    ;;
esac
. /etc/gpiotab.common
