EXTRA_OECMAKE += " -DSEL_LOGGER_MONITOR_THRESHOLD_EVENTS=ON -DSEL_LOGGER_MONITOR_THRESHOLD_ALARM_EVENTS=ON -DSEL_LOGGER_SEND_TO_LOGGING_SERVICE=ON "

SRCREV = "486e42e9db215070d631b7ac1f8f32537cb3bfe7"

FILESEXTRAPATHS_prepend := "${THISDIR}:"
SRC_URI += " file://0001-user-friendly-log-messages.patch "
