#!/bin/bash

cancel()
{
    rv=$1
    shift
    echo -e $@ 1>&2
    exit $rv
}

check_once()
{
    if [ "$TINYSPI" = "yes" ]
    then
        rv=$((0x`cat /sys/kernel/tinyspi/state_reg` & 0x8))
        case $rv in
            8) return 0;; # Active, return true
            0) return 1;; # Inactive, return false
            *) cancel 2 "Failure reading TinySPI UID state";;
        esac
    else
        status=`devmem $GPIO_UID_BTN_ADDR` || cancel 2 "Failure querying GPIO register"
        mask=$((1 << $GPIO_UID_BTN_BIT))
        case $(($status & $mask)) in
            0)     return 0;; # Pressed, return true
            $mask) return 1;; # Released, return false
            *) cancel 3 "Inconsistent data in GPIO register";;
        esac
    fi
}

led_on()
{
    if [ "$TINYSPI" = "yes" ]
    then
        echo 00000004 > /sys/kernel/tinyspi/command_bits_set
        echo 00000004 > /sys/kernel/tinyspi/command_bits_reset
    else
        echo "default-on" > /sys/class/leds/platform\:blue\:uid/trigger
    fi
}

led_off()
{
    if [ "$TINYSPI" = "yes" ]
    then
        echo 00000008 > /sys/kernel/tinyspi/command_bits_set
        echo 00000008 > /sys/kernel/tinyspi/command_bits_reset
    else
        echo "none" > /sys/class/leds/platform\:blue\:uid/trigger
    fi
}

indicate()
{
    led_on
    sleep 1
    led_off
    sleep 1
    led_on
    sleep 1
    led_off
    sleep 1
    led_on
    sleep 1
    led_off
}

. /libexec/gpio-funcs
[ -f /var/volatile/reimu.conf ] || cancel 1 "No TinySPI config file, aborting."
. /var/volatile/reimu.conf

confirm=`[ "$TINYSPI" = "yes" ] && echo "Turn off UID in less than 5 seconds to cancel." || echo "Keep holding UID for 5 seconds to confirm."`

check_once || exit 0
echo -e "\e[1;33m*** You're probably want to clean RW partition. $confirm *** \e[0m" 1>&2
sleep 5
check_once || cancel 0 "Ok, we DON'T want to clean RW partition. Exiting."

echo -e "\e[1;33mWe're REALLY want to clean RW partition. Proceeding to this...\e[0m" 1>&2
indicate

rm -rf /run/initramfs/rw/cow/

echo -e "\e[1;33m*** BMC is reverted to manufacturer's settings, rebooting. *** \e[0m" 1>&2
reboot
