OBMC_IMAGE_EXTRA_INSTALL_append = " \
  active-gpio-on \
  init-ifupdown \
  flashrom \
  buttonscripts \
  glibc-localedata-en-us \
  glibc-localedata-ru-ru \
  glibc-binary-localedata-en-us \
  glibc-binary-localedata-ru-ru \
  glibc-utils \
  nginx \
  php-fpm \
  reimu \
  mc \
  pv \
  wget \
  ethtool \
  firmware-updater \
  i2c-tools \
  overheatd \
  rawi2ctool \
  dscan \
  netsetup \
  kernel-module-tinyspi \
  kernel-module-rtc-cy14b101p \
  sqlite3 \
  initsc-lt \
  "
