#!/bin/bash

INTERFACES="eth0"
CONFIGFILES="/etc/ip-fallback/fallback"

N=0
for intf in $INTERFACES
do
    COUNTDN[$N]="no"
    ADAPTER[$N]=$intf
    TIMEOUT[$N]=0
    if [ -f $CONFIGFILES-$intf.conf ]
    then
        TIMEOUT[$N]=`grep FallbackTimeout $CONFIGFILES-$intf.conf | cut -d= -f2 2>/dev/null`
        ADDRESS[$N]=`grep FallbackAddress $CONFIGFILES-$intf.conf | cut -d= -f2 2>/dev/null`
    fi
    [ ${TIMEOUT[$N]} -gt 0 ] 2>/dev/null && COUNTDN[$N]="yes"
    if [ -f /etc/systemd/network/00-bmc-$intf.network ]
    then
        if grep -qi '^[[:space:]]*unmanaged[[:space:]]*=[[:space:]]*yes[[:space:]]*$' /etc/systemd/network/00-bmc-$intf.network
        then
            echo "Adapter $intf is unmanaged, skipping"
            COUNTDN[$N]="no"
        fi
    fi
    N=$(($N + 1))
done

initialized()
{
    ip addr list dev $1 | grep -q "inet "
}

assign()
{
    ip addr add $2 dev $1
}

# Wait until last interface will be initialized
while true
do
    do_exit=yes

    for i in `seq 0 $(($N - 1))`
    do
        if [ ${COUNTDN[$i]} = yes ]
        then
            do_exit=no
            TIMEOUT[$i]=$((${TIMEOUT[$i]} - 1))

            if initialized ${ADAPTER[$i]}
            then
                echo "Adapter ${ADAPTER[$i]} is online (${TIMEOUT[$i]} seconds remaining), stopping countdown"
                COUNTDN[$i]="no"
            fi

            if [ ${TIMEOUT[$i]} -eq 0 ]
            then
                echo "Adapter ${ADAPTER[$i]} is still offline, setting fallback address ${ADDRESS[$i]}"
                COUNTDN[$i]="no"
                assign ${ADAPTER[$i]} ${ADDRESS[$i]}
            fi
        fi
    done
    sleep 1

    if [ $do_exit = yes ]
    then
        echo "All adapters are processed, exiting"
        exit 0
    fi
done
