#!/bin/sh
### BEGIN INIT INFO
# Provides:          activeledd
# Required-Start:    initsc
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: turns on ACTIVE LED
# Description:       turns on ACTIVE LED
### END INIT INFO

GPIOBASE=292
GPIOUSE=118
GPIONUM=`expr $GPIOBASE + $GPIOUSE`

case "$1" in
    start)
        [ -d /sys/class/gpio/gpio${GPIONUM} ] || echo ${GPIONUM} > /sys/class/gpio/export
        echo out > /sys/class/gpio/gpio${GPIONUM}/direction
        echo 0 > /sys/class/gpio/gpio${GPIONUM}/value
        echo ${GPIONUM} > /sys/class/gpio/unexport
        exit 0
        ;;
    stop)
        [ -d /sys/class/gpio/gpio${GPIONUM} ] || echo ${GPIONUM} > /sys/class/gpio/export
        echo 1 > /sys/class/gpio/gpio${GPIONUM}/value
        echo in > /sys/class/gpio/gpio${GPIONUM}/direction
        echo ${GPIONUM} > /sys/class/gpio/unexport
        exit 0
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 2
        ;;
esac
