#!/bin/sh
### BEGIN INIT INFO
# Provides:          activeledd
# Required-Start:    initsc
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Turn on ACTIVE LED
# Description:       Turn on ACTIVE LED
### END INIT INFO

. /libexec/gpio-funcs

gpio=`gpio2num $GPIO_ACT_LED`

case "$1" in
    start)
        gpiowrite $gpio 0
        exit 0
        ;;
    stop)
        gpiorelease $gpio
        exit 0
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 2
        ;;
esac
