#!/bin/sh

. /etc/auto_power_on
. /libexec/gpio-funcs

spigpio=`gpio2num $GPIO_SPI_CONNECT`
pwrgpio=`gpio2num $GPIO_PWR_BTN`
rstgpio=`gpio2num $GPIO_RST_BTN`

gpiowrite $spigpio 0
gpiorelease $rstgpio
if [ "$AUTO_POWER_ON" = "on" ]
then
    gpiowrite $pwrgpio 0
    sleep 1
    gpiorelease $pwrgpio
fi
