#!/bin/bash
POWERstate=GPIO_POWER_IN
RESETstate=GPIO_RESET_IN
POWERBTN=GPIO_PWR_BTN
RESETBTN=GPIO_RST_BTN

setstate() {
  dbusstate=$(busctl get-property xyz.openbmc_project.State.Host /xyz/openbmc_project/state/host0 xyz.openbmc_project.State.Host CurrentHostState | awk '{print $2}') 
  OFF="\"xyz.openbmc_project.State.Host.HostState.Off\""
  ON="\"xyz.openbmc_project.State.Host.HostState.Running\""
  if [ "$(power_state)" == "on" ]; then
     if [ "$dbusstate" != "$ON" ]; then
        busctl set-property xyz.openbmc_project.State.Host /xyz/openbmc_project/state/host0 xyz.openbmc_project.State.Host CurrentHostState s "xyz.openbmc_project.State.Host.HostState.Running"
        busctl set-property xyz.openbmc_project.Watchdog /xyz/openbmc_project/watchdog/host0 xyz.openbmc_project.State.Watchdog ExpireAction s xyz.openbmc_project.State.Watchdog.Action.None
     fi
  else
     if [ $dbusstate != "$OFF" ]; then
        busctl set-property xyz.openbmc_project.State.Host /xyz/openbmc_project/state/host0 xyz.openbmc_project.State.Host CurrentHostState s "xyz.openbmc_project.State.Host.HostState.Off"
     fi
  fi 
}

setgpio() {
	GPIOLINE=$1
	GPIOSET1=$2
	GPIOTIME=$3
	GPIOSET2=$4
	btn=$(gpiofind $GPIOLINE)
	gpioset $btn=$GPIOSET1
	if [ "$GPIOTIME" ]; then
		sleep $GPIOTIME
		gpioset $btn=$GPIOSET2
	fi
	return 0
}


power_reset() {
	echo "Host reset"
	setgpio $RESETBTN 0 0.2 1
}

block() {
  setgpio $RESETBTN 0
  
}
unblock() {
  setgpio $RESETBTN 1
  power_reset
}


power_off() {
	echo "Host power off"
	setgpio $POWERBTN 0 0.2 1
}

power_on() {
	echo "Host power on"
	setgpio $POWERBTN 0 0.2 1
}

power_off_hard() {
	echo "Host power off hard"
	power_reset
	setgpio $POWERBTN 0 5 1
}

power_state() {
    #st=$(gpioget $(gpiofind $POWERstate))
    #if [ "$st" == "1" ]; then
    #    echo "on"
    #else
    #    echo "off"
    #fi
    if [ -f "/run/openbmc/chassis@0-on" ]; then
        echo "on"
    else
        echo "off"
    fi
}


if [ "$1" = "on" ]; then
  if [ "$(power_state)" == "off" ]; then
      power_on
  fi
elif [ "$1" = "off" ]; then
  if [ "$(power_state)" == "on" ]; then
     if [ "$2" = "hard" ]; then
      power_off_hard
     else
      power_off 
     fi
  fi
elif [ "$1" = "block" ]; then
  block
elif [ "$1" = "unblock" ]; then
  unblock
elif [ "$1" == "cycle" ]; then
  if [ "$(power_state)" == "on" ]; then
      power_off_hard
      sleep 1
  else
    echo "WARNING: Powering on server"
  fi
    power_on
elif [ "$1" == "reset" ]; then
  if [ "$(power_state)" == "on" ]; then
      power_reset
  else
    echo "ERROR: Server not powered on"
  fi
elif [ "$1" == "getstate" ]; then
    power_state
elif [ "$1" == "setstate" ]; then
   setstate 
else
    echo "Invalid parameter=$1"
    echo "usage: host [on|off|off hard|getstate|cycle|reset|setstate]";
fi

exit 0;
