#!/bin/bash
POWERstate=GPIO_POWER_IN

GPIOPOWERMON=114
GPIORESETMON=115

PON="on"
POFF="off"

ps=$(gpiofind $POWERstate)
chon=/run/openbmc/chassis@0-on


power_state() {
    st=$(gpioget $ps)
    if [ "$st" == "1" ]; then
        echo $PON
    else
        echo $POFF
    fi
}

power_monitor() {
  Res=""
    MONSTATE=$(gpiomon -n 1 -F "%o %e" 0 $GPIOPOWERMON $GPIORESETMON)
    stringarray=($MONSTATE)
    GPIOLine=${stringarray[0]}
    GPIOState=${stringarray[1]}

    if [ $GPIOLine == $GPIOPOWERMON ]; then
      if [ $GPIOState == "0" ]; then
        Res=$POFF
      else
        Res=$PON
      fi
    else 
        Res=$PON
    fi
  echo $Res
}

OLDSTATE="NONE";
NEWSTATE=$(power_state)
OLDTIME=0


while :
do
  NEWTIME=$(date +%s)
  let dT=$NEWTIME-$OLDTIME
  if [ $NEWSTATE != $OLDSTATE ] && [ "$dT" -gt "5" ] ; then
    echo $NEWTIME "NewState="$NEWSTATE
    OLDSTATE=$NEWSTATE
    OLDTIME=$NEWTIME
  
    if [ $NEWSTATE == $PON ] ; then
      host block
      systemctl restart host-plug_i2c.timer
      host unblock
      mkdir -p /run/openbmc
      touch $chon
    else
      rm -f $chon
    fi
    host setstate
  fi
  NEWSTATE=$(power_monitor)
  echo "Server" $NEWSTATE
done

