#!/bin/bash

if [ "$1" != "-h" -a "$1" != "--help" ]
then
    systemctl status rescue.target > /dev/null || error "BMC flash should be reprogrammed from single-user mode only. Execute 'init 1' to get into it."
    echo "Note: programming BMC flash chip. It will end up in immediate reboot."
    cp /usr/bin/md5sum /usr/bin/pv /bin/dd /bin/sync /usr/bin/cut /bin/rm /libexec/libfirmware-updater /tmp
    mount / -o remount,ro

    if [ ! -h /dev/mtd/bmc ]
        echo "Can't find system flash (/dev/mtd/sys). Probably board is broken?" 1>&2
        exit 1
    fi

    export PATH=/tmp:$PATH
    export REBOOT=yes
    export MTDDEV=`readlink /dev/mtd/bmc | sed 's#mtd#mtdblock#;s#../##'`
    export WGET_PARAMS

    if [ ! -b /dev/$MTDDEV ]
        echo "System flash (/dev/$MTDDEV) is missing or of wrong type." 1>&2
        exit 2
    fi
fi

/tmp/libfirmware-updater $@
