#!/bin/sh

. /libexec/gpio-funcs

spigpio=`gpio2num $GPIO_SPI_CONNECT`

export MTDDEV=mtdblock6
export WGET_PARAMS

echo "Attaching system SPI..."
gpiowrite $spigpio 1
sleep 1
firmware-updater $@
echo "Detaching system SPI..."
sleep 1
gpiowrite $spigpio 0
