#!/bin/sh

GPIOBASE=292
GPIOUSE=123

gpio=`expr $GPIOBASE + $GPIOUSE`

[ -d /sys/class/gpio/gpio$gpio ] || echo $gpio > /sys/class/gpio/export

echo out > /sys/class/gpio/gpio$gpio/direction

echo 0 > /sys/class/gpio/gpio$gpio/value

sleep 1

echo 1 > /sys/class/gpio/gpio$gpio/value

echo in > /sys/class/gpio/gpio$gpio/direction

echo $gpio > /sys/class/gpio/unexport
