#!/bin/bash

if [ ! -d /sys/class/gpio/gpiochip* ]
then
    echo "GPIO subsystem not initialized: no /sys/class/gpio/gpiochip* entry" 1>&2
    exit 240
fi

FIRSTGPIO=`ls -d /sys/class/gpio/gpiochip* | head -n1 | sed 's/.*gpiochip//'`

# Note: this is GPIO set for REIMU, MUS-A has some GPIOs absent,
# and corresponding LEDs and buttons are served through TinySPI.

case `cat /sys/devices/soc0/family` in
    AST2400)
        . /etc/gpiotab.2400
    ;;
    AST2500)
        . /etc/gpiotab.2500
    ;;
    AST2600)
        . /etc/gpiotab.2600
    ;;
esac
. /etc/gpiotab.common
