#!/bin/sh

. /libexec/gpio-funcs

# 10 seconds should be fair enough for power to became on.
LIMIT=10

gpio=`gpio2num $GPIO_POWER_IN`

while [ $LIMIT -gt 1 ]
do
    if [ `gpioread $gpio` -eq 1 ]
    then
        # We should reset watchdog only if we have ipmitool (otherwise there's no watchdog)
        [ -e `which ipmitool` ] && ipmitool mc watchdog off
        exit 0
    fi
    sleep 1
    LIMIT=`expr $LIMIT - 1`
done
exit 1
