#!/bin/bash
POWERstate=GPIO_POWER_IN
PON="on"
POFF="off"
ps=$(gpiofind $POWERstate)

power_state() {
    st=$(gpioget $ps)
    if [ "$st" == "1" ]; then
        echo $PON
    else
        echo $POFF
    fi
}

OLDSTATE="NONE";
while :
do
  NEWSTATE=$(power_state)
  if [ $NEWSTATE != $OLDSTATE ]; then
    host setstate
    OLDSTATE=$NEWSTATE
    if [ $NEWSTATE == $PON ]; then
      echo "powerOn reset"
      sleep 0.2
      host reset
    fi
  fi  
  sleep 0.1
done

