#!/bin/bash
POWERstate=GPIO_POWER_IN
PON="on"
POFF="off"
ps=$(gpiofind $POWERstate)

power_state() {
    st=$(gpioget $ps)
    if [ "$st" == "1" ]; then
        echo $PON
    else
        echo $POFF
    fi
}

OLDSTATE="NONE";
while :
do
  NEWSTATE=$(power_state)
  if [ $NEWSTATE != $OLDSTATE ]; then
    OLDSTATE=$NEWSTATE
    host setstate    
    if [ $NEWSTATE == $PON ]; then
	host block
	systemctl stop xyz.openbmc_project.FruDevice.service
	echo -n "1e78a140.i2c-bus" > /sys/bus/platform/drivers/aspeed-i2c-bus/unbind
	echo -n "1e78a1c0.i2c-bus" > /sys/bus/platform/drivers/aspeed-i2c-bus/unbind
	host unblock
	sleep 120
	echo -n "1e78a140.i2c-bus" > /sys/bus/platform/drivers/aspeed-i2c-bus/bind
	echo -n "1e78a1c0.i2c-bus" > /sys/bus/platform/drivers/aspeed-i2c-bus/bind
	systemctl start xyz.openbmc_project.FruDevice.service    
    fi
  fi  
  sleep 0.1
done

